### ISSUE TITLE
Change in Twilio sample app?

### ISSUE THREAD

**Issue by Keviningrey** [microsoft/Dynamics365-Apps-Samples#26]
Following the documentation below, it appears as if the quickstart application has changed and no longer references the functions listed below.

Follow the Twilio documentation to create a sample quickstart application: "https://www.twilio.com/docs/voice/client/javascript/quickstart"
2. Use the code from section "Twilio - Client voice" below for the "client-voice" Twilio function
3. Use the code from section "Twilio - Capability token" below for the "capability-token" Twilio function
4. Note the URL for the Twilio "capability-token" function created above. In this sample, we will use "https://twilio-sample.twil.io/capability-token"

Can this be checked and the readme updated?

**Comment by amervitz** [comment]
I'm having problems with this sample as well. The instructions for setting up the capability token seem to be incomplete. I've tried creating a new file `functions\capability-token.js` with the supplied code, and deploying the updated function, but Twilio is reporting this error in the console when the function is invoked:

```json
{
    "message": "Required parameter \"options.applicationSid\" missing.",
    "name": "Error",
    "stack": "Error: Required parameter \"options.applicationSid\" missing.\n    at new OutgoingClientScope (/var/task/node_modules/twilio/lib/jwt/ClientCapability.js:64:11)\n    at Object.exports.handler (/var/task/handlers/ZN8f356296c1d3ed74f5ff5adb6f7d1ae7.js:26:25)\n    at Object.exports.handler (/var/task/node_modules/enigma-lambda/index.js:310:10)\n    at Runtime.exports.handler (/var/task/enigma.js:17:9)\n    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
}
```

**Comment by JFulfordMS** [comment]
Same issue. This sample is broken as is.

**Comment by smarques13** [comment]
There is a variable missing in the .env file.
When you configure the OutgoingClientScope you need to populate the ApplicationSID:

capability.addScope(new ClientCapability.OutgoingClientScope({
      applicationSid: **context.TWIML_APP_SID**,
      clientName: identity,
    }));

However the step by step never mentions to create this variable in the .env file.
Just add a variable in that file:
TWIML_APP_SID = <app_sid>

You can grab this <app_sid> from twilio: 

1. go to https://www.twilio.com/console/voice/twiml/apps/ 
2. select your app in twilio
3. the <app_sid> will be the string under friendly name that starts with AP....

Save and deploy the twilio app again, after this, all should work as expected.
